### ISSUE TITLE
error: Undefined index: id    .. ->with_*('fields:some_fields except primary key')

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#23]
## Blog_m.php

```
  class Blog_m extends MY_Model {

public $table = 'blog_posts'; 
public $primary_key = 'postID';
//public $fillable = array();
public $protected = array('postID'); 

public function __construct() {
    $this->timestamps = TRUE;
    $this->soft_deletes = TRUE;
    $this->has_one['cats'] = array('Bcats_m','catID','catID');
    $this->has_one['user'] = array('User_m','id','userID');
    $this->has_many['comments'] = array('Bcomments_m', 'postID','postID');
    parent::__construct();
    }

  }
```
## User_m.php

```
 class User_m extends MY_Model {
public $table = 'users'; // you MUST mention the table name
public $primary_key = 'id'; // you MUST mention the primary key
  public $protected = array('id'); // ...Or you can set an array with the fields that cannot be filled by insert/update

public function __construct() {
    $this->has_many['blog'] = array('Blog_m','userID','id');
$this->has_many['comment'] = array('Bcomments_m','userID','id');
    parent::__construct();
    }
 }
```
# Controller:

  ## 1.
     $data = $this->blog_m->with_user()->get_all();       

```
  ### works fine
```
## 2.

```
  $data = $this->blog_m->with_user('fields:id')->get_all(); // id = primary key 

 ### works fine
```
## 3.

```
  $data = $this->blog_m->with_user('fields:username')->get_all();

 ### shows error.

A PHP Error was encountered

 Severity: Notice

 Message: Undefined index: id

 Filename: core/MY_Model.php

 Line Number: 938

 Backtrace:

  File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
```

Line: 938
Function: _error_handler

File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
     Line: 253
Function: join_temporary_results

```
   File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
```

Line: 792
        Function: _prep_after_read

```
   File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\controllers\Welcome.php
```

Line: 14
       Function: get_all

```
   File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\index.php
    Line: 292
    Function: require_once
```

**Comment by avenirer** [comment]
Hello, could you try now?

**Comment by ngangchill** [comment]
thnx.

I will try within 1 hr..I'm now out of home...

**Comment by ngangchill** [comment]
I have one more question:   how can get multiple fields by "with_*('fields:id') " method???

**Comment by avenirer** [comment]
with_*('fields:id,username,whatever,anotherfield,andonemorefield'); :)

**Comment by ngangchill** [comment]
now result  is ok bt new error occurs.

```
  A PHP Error was encountered

    Severity: Warning

    Message: Invalid argument supplied for foreach()

     Filename: core/MY_Model.php

      Line Number: 1129

     Backtrace:

           File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
       Line: 1129
         Function: _error_handler

            File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
          Line: 900
         Function: fields

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
         Line: 253
           Function: join_temporary_results

      File: C:\Program Files (x86)\EasyPHP-DevServer-                             14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
          Line: 792
           Function: _prep_after_read

         File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\controllers\Welcome.php
          Line: 18
       Function: get_all

       File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Controller.php
          Line: 87
          Function: call_user_func_array

            File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\index.php
         Line: 292
       Function: require_once
```

**Comment by ngangchill** [comment]
```
  $this->blog->with_user()->get_all();    //  everything is ok.. no errors

 $this->blog->with_user('fields:id')->get_all();  // result ok, with error

$this->blog->with_user('fields:id,username')->get_all();    // result ok, error persists
```

**Comment by avenirer** [comment]
Well... do it again... and again... maybe will go well in the end :+1:

**Comment by ngangchill** [comment]
:smile:

**Comment by ngangchill** [comment]
hey! thnx.. it is working now without error..

**Comment by ngangchill** [comment]
previous error gone but new one arises...

```
  $this->blog->with_user()->get_all();    //  everything is ok.. no errors

  $this->blog->with_user('fields:id')->get_all();  // result ok, no error while primary key present in ->whith_*('fields:primary_key,other_field')

  $this->blog->with_user('fields:id,username')->with_cats('fields:catID,catsafe')->get_all(); // no error, every is fine




         $this->blog->with_user('fields:username')->get_all();    // result ok, but shows error too cause i didnot add primary_key field
```

## Error:

```
          A PHP Error was encountered

          Severity: Notice

          Message: Undefined index: id

          Filename: core/MY_Model.php

          Line Number: 939

          Backtrace:

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
          Line: 939
          Function: _error_handler

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
          Line: 253
          Function: join_temporary_results

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
          Line: 792
          Function: _prep_after_read

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\controllers\Welcome.php
          Line: 18
          Function: get_all

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Controller.php
          Line: 87
          Function: call_user_func_array

          File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\index.php
          Line: 292
          Function: require_once
```

:cry:
