### ISSUE TITLE
soft delete does not work.   $this->blog->delete(1); 

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#25]
```
    A PHP Error was encountered

    Severity: Notice

    Message: Undefined index: postID

    Filename: core/MY_Model.php

    Line Number: 470

    Backtrace:

    File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
    Line: 470
    Function: _error_handler

    File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Model.php
    Line: 641
    Function: update

    File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\controllers\Welcome.php
    Line: 16
    Function: delete

    File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\application\core\MY_Controller.php
    Line: 87
    Function: call_user_func_array

    File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sites\blog\index.php
    Line: 292
    Function: require_once
```
## Query:

```
UPDATE `blog_posts` SET `deleted_at` = '2015-06-09 20:12:57', `updated_at` = '2015-06-09 20:12:57' WHERE `postID` IS NULL 
```

---

```
public $table = 'blog_posts';
public $primary_key = 'postID';
//public $fillable = array();
public $protected = array('postID');
```
